###
POST https://master.gusadev.com/elastic/api/v3/accessories

<> 2025-09-29T132534.400.json

###
POST https://master.gusadev.com/elastic/api/v3/accessories?
Content-Type: application/json
=
{{$placeholder}}

[]

###
/elastic/{{storeId}}/products/{{categoryId}}?
=
{{$placeholder}} &
sku = {{$placeholder}} &
urlPath = {{$placeholder}} &
isSalable = {{$placeholder}} &
linkFilters[relatesCategoryIds][] = {{$placeholder}} &
linkFilters[attributeSetId] = {{$placeholder}} &
linkFilters[relatesSizeIds][] = {{$placeholder}} &
linkFilters[relatesExtlabIds][] = {{$placeholder}} &
linkFilters[productLinks][] = {{$placeholder}} &
eyewear_type = {{$placeholder}} &
colorLimit = {{$placeholder}}

###
GET http://localhost/api/rest/catalog/category/filter/numbers?
    category_id={{$placeholder}}&
    ids={{$placeholder}}